steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/festive-magpie-369216/first-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/festive-magpie-369216/first-image']